####################################################################################################
# 'main.R' [Antonios Zagaris, Wageningen Bioveterinary Research (WUR) 2017]
# 
# This wrapper collates the various modules (in the folder 'Modules') into a sequentuial analysis of
# the datasets for the current organ (set in settings.R). The data are loaded (in presets.R) from
# the folder '../Results/(organ)/CSV_Data', where '(organ)' stands for the current organ. Details on
# the analysis process are provided in the preambles of the modules themselves; the arbiter in case
# of omissions, discrepancies etc. is obviously the code itself.
#
#
#   INPUTS
# None.
#
#   OUTPUTS
# All outputs generated by the modules called by this routine.
#
#   DEPENDENCIES
# -> all modules in folder 'Modules'
####################################################################################################
# LOAD SETTINGS AND AUXILLIARY MODULES -->>
 source('Modules/settings.R')
# LOAD SETTINGS AND AUXILLIARY MODULES <<--
####################################################################################################
# LOAD DATA AND INITIALIZE DATA STRUCTURES -->>
 source('Modules/presets.R')
# END OF LOAD DATA AND INITIALIZE DATA STRUCTURES <<--
###################################################################################################
# TABULATE PURE START/END, H2O/D2O PROFILES -->>
 source('Modules/pure.tab.R') # outcome: pure.prof.l
# END OF TABULATE PURE START/END, H2O/D2O PROFILES <<--
###################################################################################################
# TABULATE POLLUTANT PROFILES  -->>
 source('Modules/poll.tab.R') # outcome: poll.prof.df
# END OF TABULATE POLLUTANT PROFILES <<--
###################################################################################################
# TABULATE TIME LIMITS FOR START/END PURE PROFILES -->>
 source('Modules/pure.locs.R') # outcome: pure.locs.l
# END OF TABULATE TIME LIMITS FOR START/END PURE PROFILES <<--
###################################################################################################
# TABULATE TIME LIMITS FOR NON-POLLUTANT PROFILES -->>
 source('Modules/dat.locs.R') # outcome: prof.loc.l
# END OF TABULATE TIME LIMITS FOR NON-POLLUTANT PROFILES <<--
###################################################################################################
# QUANTIFY DATASETS -->>
 source('Modules/quant.R') # outcome: cnt.l, (updated) cnts.l, SR.df, (updated) SRs.l
# END OF QUANTIFY DATASETS <<--
###################################################################################################
# PLOT ALL DATASETS WITH PEAKS, VALLEYS AND (CANDIDATE) CUTOFFS -->>
 source('Modules/plot.profs.R') # outcome: plot settings; dataset plots in folder 'Results'
# END OF ALL DATASETS WITH PEAKS, VALLEYS AND (CANDIDATE) CUTOFFS <<--
###################################################################################################
# REPAIR AND REQUANTIFY DATASETS  -->>
 source('Modules/quant.fix.R') # outcome: cnt.fix.l
# END OF REPAIR AND REQUANTIFY DATASETS <<--
###################################################################################################
# PLOT REPAIRED MEAN RATIOS VS WEEKS  -->>
 source('Modules/plot.ratio.week.R') # outcome: plots ...
# END OF PLOT REPAIRED MEAN RATIOS VS WEEKS <<--
###################################################################################################

   sprintf('%s complete',organ)